[package]
name = "rust_flappy_bird"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.78"
serde-wasm-bindgen = "0.6.3"

[lib]
crate-type = ["cdylib"]
